Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$DockerfilePath = "Dockerfile"
$ComposePath = "compose.yml"
$DockerignorePath = ".dockerignore"
$DeployWorkflowPath = ".github/workflows/deploy.yml"
$RemoteDeployScriptPath = "scripts/deploy/remote-deploy.sh"

function Assert-True {
    param(
        [bool] $Condition,
        [string] $Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

Assert-True (Test-Path -LiteralPath $DockerfilePath) "Dockerfile must exist"
Assert-True (Test-Path -LiteralPath $ComposePath) "compose.yml must exist"
Assert-True (Test-Path -LiteralPath $DockerignorePath) ".dockerignore must exist"
Assert-True (Test-Path -LiteralPath $DeployWorkflowPath) "deploy workflow must exist"
Assert-True (Test-Path -LiteralPath $RemoteDeployScriptPath) "remote deploy rollback script must exist"

$dockerfile = Get-Content -Raw -LiteralPath $DockerfilePath
$compose = Get-Content -Raw -LiteralPath $ComposePath
$dockerignore = Get-Content -Raw -LiteralPath $DockerignorePath
$workflow = Get-Content -Raw -LiteralPath $DeployWorkflowPath
$remoteScript = Get-Content -Raw -LiteralPath $RemoteDeployScriptPath

Assert-True ($dockerfile -match "FROM eclipse-temurin:21\.0\.4_7-jdk-jammy AS build") "Dockerfile must pin a Java 21 build image"
Assert-True ($dockerfile -match "FROM eclipse-temurin:21\.0\.4_7-jre-jammy AS runtime") "Dockerfile must pin a Java 21 runtime image"
Assert-True ($dockerfile -match "COPY gradlew settings\.gradle build\.gradle") "Dockerfile must build through the Gradle wrapper"
Assert-True ($dockerfile -match "\./gradlew --no-daemon clean bootJar -x test -x integrationTest") "Dockerfile must package the Spring Boot jar"
Assert-True ($dockerfile -match "apt-get install -y --no-install-recommends curl") "Runtime container must include curl for health checks"
Assert-True ($dockerfile -match "USER spring:spring") "Runtime container must use a non-root user"
Assert-True ($dockerfile -match "EXPOSE 8080") "Dockerfile must expose the Spring server port"
Assert-True ($dockerfile -match 'ENTRYPOINT \["java".*"-jar", "/app/app\.jar"\]') "Dockerfile must run the boot jar"
Assert-True ($dockerfile -notmatch "python|pip|requirements\.txt|uvicorn|main:app") "Dockerfile must not contain the removed FastAPI placeholder"

Assert-True ($dockerignore -match "(?m)^\.git$") ".dockerignore must exclude git metadata"
Assert-True ($dockerignore -match "(?m)^build$") ".dockerignore must exclude local build output"
Assert-True ($dockerignore -match "(?m)^\.env$") ".dockerignore must exclude dotenv secrets"
Assert-True ($dockerignore -match "(?m)^\.env\.\*$") ".dockerignore must exclude dotenv variants"

Assert-True ($compose -match 'image: naeil-bank-backend:\$\{APP_VERSION:\?APP_VERSION is required\}') "Compose must fail closed when APP_VERSION is absent"
Assert-True ($compose -match '"\$\{APP_PORT:\?APP_PORT is required\}:8080"') "Compose must map explicit external branch port to internal 8080"
Assert-True ($compose -match 'SPRING_PROFILES_ACTIVE: \$\{APP_PROFILE:\?APP_PROFILE is required\}') "Compose must use explicit APP_PROFILE"
Assert-True ($compose -notmatch "deploy") "Compose must not default to a nonexistent deploy profile"
Assert-True ($compose -match 'SPRING_DATASOURCE_URL: jdbc:postgresql://naeil-db:5432/\$\{DB_NAME:\?DB_NAME is required\}') "Compose must connect through naeil-db:5432 with explicit DB_NAME"
Assert-True ($compose -match "SPRING_DATASOURCE_USERNAME: naeil") "Compose must use the server DB user"
Assert-True ($compose -match 'SPRING_DATASOURCE_PASSWORD: \$\{POSTGRES_PASSWORD:\?POSTGRES_PASSWORD is required\}') "Compose must require POSTGRES_PASSWORD from server env"
Assert-True ($compose -match 'JWT_SECRET: \$\{JWT_SECRET:\?JWT_SECRET is required\}') "Compose must require JWT_SECRET at runtime"
Assert-True ($compose -match 'KAKAO_CLIENT_ID: \$\{KAKAO_CLIENT_ID:\?KAKAO_CLIENT_ID is required\}') "Compose must require Kakao client id at runtime"
Assert-True ($compose -match 'KAKAO_CLIENT_SECRET: \$\{KAKAO_CLIENT_SECRET:\?KAKAO_CLIENT_SECRET is required\}') "Compose must require Kakao client secret at runtime"
Assert-True ($compose -match 'KAKAO_REDIRECT_URI: \$\{KAKAO_REDIRECT_URI:\?KAKAO_REDIRECT_URI is required\}') "Compose must require Kakao redirect uri at runtime"
Assert-True ($compose -match 'OPENAI_API_KEY: \$\{OPENAI_API_KEY:\?OPENAI_API_KEY is required\}') "Compose must require OpenAI API key at runtime"
Assert-True ($compose -notmatch "OPENAI_MODEL:") "Compose must not expose removed non-binding OPENAI_MODEL"
Assert-True ($compose -match 'OPENAI_MEAL_MODEL: \$\{OPENAI_MEAL_MODEL:\?OPENAI_MEAL_MODEL is required\}') "Compose must require meal OpenAI model"
Assert-True ($compose -match 'OPENAI_FACE_MODEL: \$\{OPENAI_FACE_MODEL:\?OPENAI_FACE_MODEL is required\}') "Compose must require face OpenAI model"
Assert-True ($compose -match 'OPENAI_TIMEOUT: \$\{OPENAI_TIMEOUT:\?OPENAI_TIMEOUT is required\}') "Compose must require OpenAI timeout"
Assert-True ($compose -match 'VAPID_PUBLIC_KEY: \$\{VAPID_PUBLIC_KEY:\?VAPID_PUBLIC_KEY is required\}') "Compose must require VAPID public key at runtime"
Assert-True ($compose -match 'VAPID_PRIVATE_KEY: \$\{VAPID_PRIVATE_KEY:\?VAPID_PRIVATE_KEY is required\}') "Compose must require VAPID private key at runtime"
Assert-True ($compose -match 'VAPID_SUBJECT: \$\{VAPID_SUBJECT:\?VAPID_SUBJECT is required\}') "Compose must require VAPID subject at runtime"
Assert-True ($compose -match 'CORS_ORIGINS: \$\{CORS_ORIGINS:\?CORS_ORIGINS is required\}') "Compose must require CORS origins at runtime"
Assert-True ($compose -match 'APP_TIMEZONE_DEFAULT_ZONE: \$\{APP_TIMEZONE_DEFAULT_ZONE:\?APP_TIMEZONE_DEFAULT_ZONE is required\}') "Compose must require Todo3 timezone property env"
Assert-True ($compose -match 'TZ: \$\{APP_TIMEZONE_DEFAULT_ZONE:\?APP_TIMEZONE_DEFAULT_ZONE is required\}') "Compose must derive container timezone from Todo3 timezone env"
Assert-True ($compose -match 'APP_SCHEDULING_MORNING_STATEMENT_CRON: \$\{APP_SCHEDULING_MORNING_STATEMENT_CRON:\?APP_SCHEDULING_MORNING_STATEMENT_CRON is required\}') "Compose must require Todo3 scheduling cron env"
Assert-True ($compose -match 'APP_UPLOAD_MAX_INPUT_SIZE: \$\{APP_UPLOAD_MAX_INPUT_SIZE:\?APP_UPLOAD_MAX_INPUT_SIZE is required\}') "Compose must require Todo3 upload input size env"
Assert-True ($compose -match 'APP_UPLOAD_MAX_GENERATED_SIZE: \$\{APP_UPLOAD_MAX_GENERATED_SIZE:\?APP_UPLOAD_MAX_GENERATED_SIZE is required\}') "Compose must require Todo3 upload generated size env"
Assert-True ($compose -notmatch "APP_TIMEZONE:|APP_SCHEDULING_ENABLED:|UPLOAD_MAX_BYTES:") "Compose must not expose removed non-binding app env names"
Assert-True ($compose -match "SPRING_JPA_HIBERNATE_DDL_AUTO: validate") "Compose must prevent Hibernate schema creation in deploy"
Assert-True ($compose -match 'SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"') "Compose must tolerate an existing schema baseline"
Assert-True ($compose -match "actuator/health/readiness") "Compose healthcheck must target readiness"
Assert-True ($compose -match "curl -fsS http://127\.0\.0\.1:8080/actuator/health/readiness") "Compose healthcheck must use runtime curl"
Assert-True ($compose -match "name: app_default") "Compose must attach to the existing DB network"
Assert-True ($compose -notmatch "DATABASE_URL|postgresql://naeil:\$\{POSTGRES_PASSWORD\}") "Compose must not embed a password URL"

Assert-True ($workflow -match "branches: \[main, develop\]") "Deploy workflow must keep main/develop branch deployment"
Assert-True ($workflow -match "permissions:\s*\r?\n\s*contents:\s*read") "Deploy workflow must use least contents permission"
Assert-True ($workflow -match "concurrency:") "Deploy workflow must define concurrency"
Assert-True ($workflow -match "Test and package deploy commit") "Deploy workflow must gate SSH on local tests"
Assert-True ($workflow -match "\./gradlew --no-daemon clean test integrationTest bootJar") "Deploy workflow must test and package before SSH"
Assert-True ($workflow -match "Validate Docker deploy package") "Deploy workflow must validate Docker deploy package before SSH"
Assert-True ($workflow -match "bash -n scripts/deploy/remote-deploy\.sh") "Deploy workflow must syntax-check remote deploy script before SSH"
Assert-True ($workflow -match "docker compose config") "Deploy workflow must validate compose interpolation before SSH"
Assert-True ($workflow -match 'docker build --tag "naeil-bank-backend:\$\{APP_VERSION\}" \.') "Deploy workflow must build the Docker image before SSH"
Assert-True ($workflow.IndexOf("Test and package deploy commit") -lt $workflow.IndexOf("Validate Docker deploy package")) "Gradle gate must run before Docker gate"
Assert-True ($workflow.IndexOf("Validate Docker deploy package") -lt $workflow.IndexOf("Setup SSH")) "Docker gate must run before SSH"
Assert-True ($workflow -match "APP_PROFILE: \$\{\{ steps\.cfg\.outputs\.profile \}\}") "Deploy workflow must provide APP_PROFILE to Docker gate"
Assert-True ($workflow -match "JWT_SECRET: ci-placeholder-jwt-secret") "Deploy workflow must provide non-secret JWT fixture to compose config"
Assert-True ($workflow -match "KAKAO_CLIENT_ID: ci-placeholder-kakao-client-id") "Deploy workflow must provide non-secret Kakao fixture to compose config"
Assert-True ($workflow -match "OPENAI_API_KEY: ci-placeholder-openai-key") "Deploy workflow must provide non-secret OpenAI fixture to compose config"
Assert-True ($workflow -notmatch "OPENAI_MODEL:") "Deploy workflow must not provide removed non-binding OPENAI_MODEL fixture"
Assert-True ($workflow -match "OPENAI_MEAL_MODEL: gpt-4\.1-mini") "Deploy workflow must provide non-secret meal model fixture"
Assert-True ($workflow -match "OPENAI_FACE_MODEL: gpt-4\.1-mini") "Deploy workflow must provide non-secret face model fixture"
Assert-True ($workflow -match "OPENAI_TIMEOUT: 30s") "Deploy workflow must provide non-secret OpenAI timeout fixture"
Assert-True ($workflow -match "VAPID_PRIVATE_KEY: ci-placeholder-vapid-private") "Deploy workflow must provide non-secret VAPID fixture to compose config"
Assert-True ($workflow -match "CORS_ORIGINS: http://localhost:5173") "Deploy workflow must provide non-secret CORS fixture to compose config"
Assert-True ($workflow -match "APP_TIMEZONE_DEFAULT_ZONE: Asia/Seoul") "Deploy workflow must provide non-secret Todo3 timezone fixture"
Assert-True ($workflow -match 'APP_SCHEDULING_MORNING_STATEMENT_CRON: "0 0 8 \* \* \*"') "Deploy workflow must provide non-secret Todo3 scheduling cron fixture"
Assert-True ($workflow -match "APP_UPLOAD_MAX_INPUT_SIZE: 10MB") "Deploy workflow must provide non-secret Todo3 upload input fixture"
Assert-True ($workflow -match "APP_UPLOAD_MAX_GENERATED_SIZE: 20MB") "Deploy workflow must provide non-secret Todo3 upload generated fixture"
Assert-True ($workflow -notmatch "APP_TIMEZONE:|APP_SCHEDULING_ENABLED:|UPLOAD_MAX_BYTES:") "Deploy workflow must not provide removed non-binding app env fixtures"
Assert-True ($workflow -match "--exclude \.env") "Deploy workflow must not sync local dotenv files"
Assert-True ($workflow -match "--exclude '\.env\.\*'") "Deploy workflow must not sync local dotenv variants"
Assert-True ($workflow -match "dir=backend-prod") "Deploy workflow must keep main deployment directory"
Assert-True ($workflow -match "port=8000") "Deploy workflow must keep main deployment port"
Assert-True ($workflow -match "db=naeil_bank") "Deploy workflow must keep main DB"
Assert-True ($workflow -match "profile=prod") "Deploy workflow must set prod profile for main"
Assert-True ($workflow -match "dir=backend-dev") "Deploy workflow must keep develop deployment directory"
Assert-True ($workflow -match "port=8001") "Deploy workflow must keep develop deployment port"
Assert-True ($workflow -match "db=naeil_bank_dev") "Deploy workflow must keep develop DB"
Assert-True ($workflow -match "profile=dev") "Deploy workflow must set dev profile for develop"
Assert-True ($workflow -notmatch "rsync -az --delete") "Deploy workflow must not use broad rsync delete"
Assert-True ($workflow -match "APP_VERSION: \$\{\{ github\.sha \}\}") "Deploy workflow must build an immutable commit-tagged image in CI"
Assert-True ($workflow -match "'\$\{\{ github\.sha \}\}'") "Deploy workflow must pass immutable commit SHA to remote deploy script"
Assert-True ($workflow -match "bash scripts/deploy/remote-deploy\.sh") "Deploy workflow must delegate remote deployment to rollback script"
Assert-True ($workflow -match "'/home/ubuntu/app/\.env'") "Deploy workflow must pass existing server env file path without printing contents"
Assert-True ($workflow -notmatch "docker compose --env-file /home/ubuntu/app/\.env -p .* up -d --build") "Deploy workflow must not inline deploy without rollback"
Assert-True ($workflow -match "Cleanup runner credentials") "Deploy workflow must remove runner SSH key"
Assert-True ($workflow -notmatch 'echo\s+["'']?\$\{\{\s*secrets\.SERVER_SSH_KEY') "Deploy workflow must not echo the SSH key expression"
Assert-True ($workflow -match 'printf ''%s\\n'' "\$SERVER_SSH_KEY"') "Deploy workflow must write SSH key from masked env"

Assert-True ($remoteScript -match "set -Eeuo pipefail") "Remote deploy script must run with strict shell settings"
Assert-True ($remoteScript -match "APP_PROFILE must be dev or prod") "Remote deploy script must reject unknown profiles"
Assert-True ($remoteScript -match "docker inspect --format '{{\.Config\.Image}}'") "Remote deploy script must inspect previous running image"
Assert-True ($remoteScript -match 'APP_VERSION="\$app_version"[\s\S]*docker compose --env-file "\$env_file" -p "\$project_name" ps -q api') "Remote deploy script must provide required compose env while inspecting previous container"
Assert-True ($remoteScript -match "image_version") "Remote deploy script must derive rollback version from previous image"
Assert-True ($remoteScript -match "write_state") "Remote deploy script must persist previous healthy non-secret config"
Assert-True ($remoteScript -match "restore_previous") "Remote deploy script must implement rollback"
Assert-True ($remoteScript -match 'APP_VERSION="\$rollback_version"') "Remote deploy script must restore previous image tag during rollback"
Assert-True ($remoteScript -match "DEPLOY_FORCE_READINESS_FAILURE") "Remote deploy script must include a deterministic negative-path hook"
Assert-True ($remoteScript -match "actuator/health/readiness") "Remote deploy script must verify unauthenticated readiness endpoint"
Assert-True ($remoteScript -notmatch "docker compose config") "Remote deploy script must not print server env via compose config"
Assert-True ($remoteScript -notmatch "cat .*env|printenv|env \|") "Remote deploy script must not print env-file contents"

"PASS deploy contract tests"
